name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g firebase-tools
      - run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_INVENTARIS_KLEUTERBOEKEN_BSOW }}"

